apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: ph120805-ambulance-ufe-content
spec:
  microFrontend: ph120805-ambulance-ufe
  element: ph120805-ambulance-wl-list
  displayRules:
    - allOf:
        - context-name: main-content
        - path: "^(\\.?/)?ph120805-ambulance-wl(/.*)?$"
